services:
  frontend:
    build:
      context: '/frontend'
      target: prod
      args:
        VITE_CRYPTO_KEY: ${CRYPTO_KEY}
        VITE_API_BASE: ${API_BASE}
    container_name: "test-frontend-prod"
    environment:
      VITE_CRYPTO_KEY: ${CRYPTO_KEY}
      VITE_API_BASE: ${API_BASE_PROD}
    ports:
      - "80:80"
    working_dir: /app
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: './backend'
      target: prod
    container_name: 'test-backend-prod'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TIME: ${JWT_ACCESS_TIME}
      JWT_REFRESH_TIME: ${JWT_REFRESH_TIME}
    working_dir: '/app'
    expose:
      - "8080"
    restart: unless-stopped

  db:
    image: 'postgres:17.7-alpine'
    container_name: 'test-postgres-db-prod'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    expose:
      - '5432'
    restart: unless-stopped

volumes:
  db_data:
